/*
The purpose of this code is to create graphs
based off of the text files generated by EPD
calibration (EW PP TT ADC format) and to then
line fit those graphs to an average value (day
vs ADC per tile). It then will plot the
chi2/ndf of each fit line to see if there are
any trends of drift from an average value over
the days.

-Skipper Kagamaster

Update: Calibration for Run20 7.7 GeV FXT
Author: Ding Chen
Date: Nov. 23, 2020
*/

/// C++ Headers
#include <iostream>
#include <fstream>

/// ROOT Headers
#include "TFile.h"
#include "TChain.h"
#include "TSystem.h"
#include "TH1.h"
#include "TMath.h"
#include "TTree.h"

void DayFitsHistos(const Char_t *inFile = "NMipConstAll_R21_7p7_COL_day.txt")
{

/// This is what I'll want to do for saving; I need to define day.
//Form("NmipsDay%d",day);

/// Let's make stuff to hold the data.
Double_t tAve[2][12][31];
Double_t tAveErr[2][12][31];
Double_t tChi2[2][12][31];
Int_t day, ew, pp, tt, days, total;
Double_t adc, err, ey;
int runStart = 22038;
int runEnd = 22044;
int dayStart = 22038;
int dayEnd = 22044;
int daysUsed = dayEnd-dayStart+1;
// if ((dayStart>109)&&(dayStart<116))
// {
//   daysUsed += 1;
// }
// else if (dayStart>116)
// {
//   daysUsed += 2;
// }
// if ((dayEnd>109)&&(dayEnd<116))
// {
//   daysUsed -= 1;
// }
// else if (dayEnd>116)
// {
//   daysUsed -= 2;
// }
days = runEnd-runStart+1;
int runTotal = 4464*(days);
double data[runTotal];
Double_t nMipADC[days][2][12][31];
Double_t nMipError[days][2][12][31];
std::ofstream NmipFile(Form("/mnt/c/Users/pjska/github/EpdCalibration/result_R21_7p7_COL/Nmip_Day_%d.txt",dayStart),ofstream::out);
//double data[4464];

/// This bit of code is to read the text file and give ROOT some usable data.
    std::ifstream input(inFile);

    for (int i = 0; i < runTotal; i+=1)
    //for (int i = 0; i < 4464; i+=1)
    {
        input >> data[i];
    }

/// And now we'll fill our array with the data (arranged by ew, pp, tt).
    for (int i = 0; i < runTotal; i+=6)
    {
      // if (data[i] < 109)
      // {
         // day = (int) data[i];
      // }
      // else if ((data[i]>109)&&(data[i]<116))
      // {
      //   day = (int) data[i]-1;
      // }
      // else if (data[i] > 116)
      // {
      //   day = (int) data[i]-2;
      // }
      day = (int) data[i];


      ew = (int) data[i+1];
      pp = (int) data[i+2];
      tt = (int) data[i+3];
      adc = data[i+4];
      err = data[i+5];
      ey = 0;
      // if((day == 172)||(day == 173))
      // {
      //   std::cout << "adc = " << adc << std::endl;
      // }
      nMipADC[day-runStart][ew][pp-1][tt-1] = adc;
      nMipError[day-runStart][ew][pp-1][tt-1] = err;
    }

/// Histograms to show the ADC variance by day/tile.
TH2D *hADCDelta[24];

for (int i = 0; i < 2; ++i) // only east side
{
  for (int j = 0; j < 12; ++j)
  {
    int l = j+ i*12;
    hADCDelta[l] = new TH2D(Form("hADCDelta%d",l),
      Form("1st MIP MPV Delta for EW%d, PP%d;Day;TT",i,j+1),
        daysUsed,dayStart-0.5,dayEnd+0.5,31,0.5,31.5);
  }
}

/// Loop to get averages for all tiles.
TCanvas *c1 = new TCanvas("c1","Day vs 1st nMip",490,175,1332,799);
/// Use this to divide the canvas.
	//c1->Divide(4,8,0,0);
TGraphErrors* gr[31]; //= new TGraphErrors();
for (int i = 0; i < 2; ++i) // only east side
{
  ew = i;
  for (int j = 0; j < 12; ++j)
	  {
	  	pp = j+1;
    for (int k = 0; k < 31; ++k)
	  	{
	  		tt = k+1;
        gr[k] = new TGraphErrors();
        for (int day = dayStart; day < dayEnd+1; ++day)
        {
          int d;
          // if (day<109)
          // {
            d=day-runStart;
          // }
          // else if (day==109)
          // {
          //   continue;
          // }
          // else if ((day>109)&&(day<116))
          // {
          //   d=day-runStart-1;
          // }
          // else if (day==116)
          // {
          //   continue;
          // }
          // else if (day>116)
          // {
          //   d=day-runStart-2;
          // }
          gr[k]->SetPoint(d,day,nMipADC[d][i][j][k]);
          gr[k]->SetPointError(d,0,nMipError[d][i][j][k]);
        }

      /// Just some graphing nonsense.
      gr[k]->GetXaxis()->SetTitle("Run serial number");
      gr[k]->GetXaxis()->CenterTitle(true);
      gr[k]->GetXaxis()->SetNdivisions(310);
      gr[k]->GetXaxis()->SetLabelFont(42);
      gr[k]->GetXaxis()->SetLabelOffset(0.013);
      gr[k]->GetXaxis()->SetTitleSize(0.05);
      gr[k]->GetXaxis()->SetTitleOffset(0.93);
      gr[k]->GetXaxis()->SetTitleFont(42);
      gr[k]->GetYaxis()->SetTitle("ADC");
      gr[k]->GetYaxis()->SetNdivisions(506);
      gr[k]->GetYaxis()->SetLabelFont(42);
      gr[k]->GetYaxis()->SetLabelSize(0.05);
      gr[k]->GetYaxis()->SetTitleSize(0.05);
      gr[k]->GetYaxis()->SetTitleOffset(0.96);
      gr[k]->GetYaxis()->SetTitleFont(42);
      gr[k]->SetMarkerStyle(6);
   		gr[k]->Draw("AP");
   		gr[k]->Fit("pol0","q");
      TFitResultPtr r = gr[k]->Fit("pol0","Sq");
      TMatrixDSym cov = r->GetCovarianceMatrix();
      tChi2[i][j][k] = r->Chi2()/r->Ndf();
      Double_t Ave  = r->Value(0);
      Double_t aErr = r->ParError(0);
      NmipFile << Form("%d \t%d \t%d \t%d \t%lf \t0.0",dayStart,ew,pp,tt,Ave);
      // NmipFile << Form("%d \t%d \t%d \t%d \t%lf",dayStart,ew,pp,tt,Ave);
      NmipFile << endl;
      tAve[i][j][k] = Ave;
      tAveErr[i][j][k] = aErr;
   	  }
  }
}

/// Loop to fill the histograms.
for (int i = 0; i < 2; ++i) // only east side
{
  ew = i;
  for (int j = 0; j < 12; ++j)
  {
    pp = j+1;
    int l = j + i*12;
    for (int k = 0; k < 31; ++k)
    {
      tt = k+1;
      for (int n = 0; n < daysUsed; ++n)
      {
        // if (dayStart < 109)
        // {
          day = dayStart;
        // }
        // else if ((dayStart>109)&&(dayStart<116))
        // {
        //   day = dayStart -1;
        // }
        // else if (dayStart > 116)
        // {
        //   day = dayStart -2;
        // }

        int current = day-runStart+n;
        int thisDay;

        // if (day + n < 109)
        // {
          thisDay = day + n;
        // }
        // else if ((day + n >108)&&(day + n <115))
        // {
        //   thisDay = day + n + 1;
        // }
        // else if (day + n > 114)
        // {
        //   thisDay = day + n + 2;
        // }
        double spread = TMath::Abs(nMipADC[current][i][j][k]-tAve[i][j][k]);

        // if(thisDay == 172 || thisDay == 173)
        // {
        //   std::cout<<"thisDay = " <<thisDay<<std::endl;
        //   std::cout<<"nMip = " <<nMipADC[current][i][j][k]<<std::endl;
        //   std::cout<<"tAve = " <<tAve[i][j][k]<<std::endl;
        //   std::cout<<"Delta = " <<spread<<std::endl;
        //
        // }
        hADCDelta[l]->Fill(thisDay,tt,spread);
      }
    }
  }
}
TCanvas *c2 = new TCanvas("c2","Average per Tile",490,175,1332,799);
c2->SaveAs(Form("/mnt/c/Users/pjska/github/EpdCalibration/result_R21_7p7_COL/ADCDelta_%d_%d.pdf[",dayStart,dayEnd));
for (int i = 0; i < 2; ++i) // only east side
{
  for (int j = 0; j < 12; ++j)
  {
    int l = j + i*12;
    hADCDelta[l]->SetStats(kFALSE);
    hADCDelta[l]->Draw("colz");
    c2->SaveAs(Form("/mnt/c/Users/pjska/github/EpdCalibration/result_R21_7p7_COL/ADCDelta_%d_%d.pdf",dayStart,dayEnd));
  }
}
c2->SaveAs(Form("/mnt/c/Users/pjska/github/EpdCalibration/result_R21_7p7_COL/ADCDelta_%d_%d.pdf]",dayStart,dayEnd));
}
